name: bdo_boats
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  localstore: ^1.4.0
  percent_indicator: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splashscreen.jpg
    - assets/boat_materials/
    - assets/boat_routes/